[package]
name = "state_channel_node"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ed25519-dalek = "2.0"
rocksdb = "0.21"

[dev-dependencies]
rustfmt = "1.6.0"
clippy = "0.1.70"

[profile.dev]
opt-level = 1
debug = true
